apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: production
data:
  config.yaml: |
    db:
      host: "postgres-auth-service"
      port: 5432
      user: "auth_user"
      password: "auth_password"
      name: "auth_db"
      dsn: "postgres://auth_user:auth_password@postgres-auth-service:5432/auth_db?sslmode=disable"
    redis:
      addr: "redis:6379"
    kafka:
      broker: "kafka:9092"
    jwt:
      privateKeyPath: "/etc/secrets/jwt-private.pem"
      publicKeyPath: "/etc/secrets/jwt-public.pem"