env: development

server:
  port: 50051

database:
  host: "localhost"
  port: 5432
  user: "auth_user"
  password: "dev_password"    # 개발 환경용 패스워드 (실제 운영에서는 시크릿 관리)
  name: "auth_db_dev"

redis:
  addr: "localhost:6379"
  db: 0

kafka:
  broker: "localhost:9092"
  topic_prefix: "auth.events."

jwt:
  private_key_path: "./configs/keys/dev/jwt-private.pem"
  public_key_path: "./configs/keys/dev/jwt-public.pem"
  access_token_expiry: "15m"
  refresh_token_expiry: "7d"

logging:
  level: "debug"
  format: "json"
