env: development

server:
  port: 50051

database:
  host: "4.206.162.3"
  port: 5432
  user: "auth_user"
  password: "test_password"    # 개발 환경용 패스워드 (실제 운영에서는 시크릿 관리)
  name: "auth_db_test"

redis:
  addr: "4.206.162.3:6379"
  db: 0

kafka:
  broker: "4.206.162.3:29092"  # Kafka는 29092 포트로 조정 (Docker Compose 매핑)
  topic_prefix: "auth.events."

jwt:
  private_key_path: "/Users/jinhyeok/IV-auth-service/configs/keys/dev/jwt-private.pem"
  public_key_path: "/Users/jinhyeok/IV-auth-service/configs/keys/dev/jwt-public.pem"
  access_token_expiry: "15m"
  refresh_token_expiry: "7d"

logging:
  level: "debug"
  format: "json"