env: production

server:
  port: 50051

database:
  host: "postgres-auth-service"  # Kubernetes 서비스명 또는 클라우드 DB 엔드포인트
  port: 5432
  user: "auth_user"
  password: "prod_password"      # 운영 환경에서는 반드시 시크릿 관리 도구를 통해 주입
  name: "auth_db_prod"

redis:
  addr: "redis-auth-service:6379"
  db: 0

kafka:
  broker: "kafka-auth-service:9092"
  topic_prefix: "auth.events."

jwt:
  private_key_path: "/etc/secrets/jwt-private.pem"
  public_key_path: "/etc/secrets/jwt-public.pem"
  access_token_expiry: "15m"
  refresh_token_expiry: "7d"

logging:
  level: "info"
  format: "json"
